data:
  train:
    directory: resources/signals
    frequency_length: 360
    time_truncation: 4096
    aggregation_window: 32
    noise_normal_std: 1.0587912
  validation:
    directory: resources/train
    labels: resources/train_labels.csv

model:
  model_name: resnext50d_32x4d
  pretrained: True
  drop_rate: 0.1
  drop_path_rate: 0.2
  num_classes: 1
  in_chans: 4

optim:
  optimizer:
    lr: 2e-4
    betas: [0.9, 0.999]
    eps: 1e-6
    weight_decay: 1e-5
  scheduler:
    min_lr: 1e-5

train:
  name: resnext50d_32x4d
  epochs: 20
  batch_size: 64
  accumulate_grad_batches: 1
  validation_interval: 0.25
  gradient_clip_val: 0
  log_every_n_steps: 10
